✅(backend) fix randomly failing test due to delay before check
The signature is issued when the request is made but we only check the
timestamp after a few other lines of code/checks. In some cases,
this was causing a 1s difference in the timestamp (because the request
was made at the just a fraction of a second before the next instruction...)
and the test was failing:

> assert response["X-Amz-Date"] == timezone.now().strftime("%Y%m%dT%H%M%SZ")
AssertionError: assert equals failed '20250504T175307Z'  '20250504T175308Z'